### PR TITLE
Add initial CSV parser.

### LINKED ISSUE #14: Add CSV import
For storing multiple columns at once a CSV import feature would be helpful and could improve performance if data frames with many columns/properties should be stored.

### PR DESCRIPTION
**Pull request by kenwenzel**
Adds a CSV parser that converts CSV files into a set of KVIN tuples.

Fixes #14

### CODE REVIEW

**Comment by kenwenzel** [comment]
> @kenwenzel Would it be better to set the default seperator to semicolon ";" instead of comma "," because in European countries, a comma is reserved for the decimal symbol, and the list separator is generally set to semicolon ?

@m-alreeni According to the OpenCSV source code their default separator is `,`. I would stay with this "default". Don't you think so?
About decimal symbols: Thank you for bringing this up. This could currently be a problem as I don't know what `Double.parseDouble(...)` is actually doing in this case.

**Comment by m-alreeni** [comment]
`This could currently be a problem as I don't know what Double.parseDouble(...) is actually doing in this case.`
could it be parsed from NumberFormat related to the Locale object..?

**Comment by kenwenzel** [comment]
@m-alreeni How do we proceed here?

**Comment by kenwenzel** [comment]
Do you agree to merge this or are any issues left?

**Pull request merged**
